language: ruby
rvm:
- 2.5.3

before_install:
  - gem install bundler
before_script:
  - bundle exec rake db:{drop,create,migrate,seed}
script:
  - bundle exec rspec

# script:
#   — db:create
#   — db:migrate
#   — rspec